### ISSUE TITLE
Remove lints package and use lint instead with custom rules

### ISSUE THREAD

**Issue by alexrintt** [alexrintt/shirou#3]
This is the new analysis_options we will be working with:

```yaml
include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_use_package_imports: false
    avoid_relative_lib_imports: false
    always_specify_types: true
    unawaited_futures: true
```
